services:
  acme:
    image: registry.ohrenpirat.de:5000/mwildt/acme-helper
    build:
      context: .
      dockerfile: acme.containerfile
    environment:
      ACME_FILE: "./path/to/acme.json"
      CERTIFICATE_DIR: "./path/to/certs"